apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app-container
        image: fakabbir/simpleapp:v2
        ports:
        - containerPort: 8000
        env:
        - name: ENV_VAR
          value: "production"
