apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
spec:
  type: LoadBalancer  # Use NodePort for internal access only
  selector:
    app: simple-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
